### ISSUE TITLE
[1pt] Set up kanban board

### ISSUE THREAD

**Issue by virag-ky** [Berkay-akbas/Catalog-of-my-things#8]
Kanban board link: https://github.com/Berkay-akbas/Catalog-of-my-things/projects/1

3 people:
@virag-ky : Team member #1
@ademibowale : Team member #2
@Berkay-akbas : Team member #3

**Comment by Bondok6** [comment]
## Hi Team 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
- link to their GitHub project ✅
- information about the number of people in their group ✅
- Create card with the number of points in the \[Xpt\] ✅

## Required Changes ♻️

- [ ] Great job 💯, But I noticed that you didn't add all the tasks and according to the requirements, All tasks from the list for a given student in [the project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) file have a corresponding card in the Kanban board. 👌

## Optional suggestions

- [ ] Please, Assign all team members to the card if it is (a Group Task) 👍

| ⭕ | ✅|  
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/194850789-23a8d18d-c24c-4588-917b-3e7bae104030.PNG" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/194850821-54065e4f-d67a-4147-b64c-e60a2074eac4.PNG" width="500" /> |


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the ISSUE thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by virag-ky** [comment]
Added all the other tasks and assigned everyone for the group tasks.

**Comment by BenMukebo** [comment]
### Hi @virag-ky, @Bondok6, @ademibowale, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Link to your GitHub project. is present ✔️  
- The information about the number of people in your group is present ✔️ 
- Each requiremnts have at least one corresponding card in the Kanban board. ✔️ 
- All cards are assigned to team members. ✔️  


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
